image:
  repository: quay.io/eformat/trino-query-ui
  tag: latest
  pullPolicy: Always

replicas: 1

trinoUpstream: trino:8080

service:
  port: 8080

route:
  enabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
