#!/usr/bin/env bash
# Upload training data, reward function, and BIRD databases to the shared PVC.
#
# Run from an RHOAI workbench where the PVC is mounted, or use
# oc rsync to copy from a local machine.
#
# Usage:
#   ./scripts/upload_to_pvc.sh [pvc_mount_path]
#
# Default PVC mount: /opt/app-root/src/shared

set -euo pipefail

PVC_MOUNT="${1:-/opt/app-root/src/shared}"
TARGET="$PVC_MOUNT/text2sql"

echo "==> Uploading rl-sql artifacts to PVC at $TARGET"

mkdir -p "$TARGET"/{reward,bird_databases}

# Reward function module
echo "    Copying reward/ module..."
cp -r reward/*.py "$TARGET/reward/"

# Training data (generated by notebook 01)
if [ -f data/sft_train_data.jsonl ]; then
    echo "    Copying SFT training data..."
    cp data/sft_train_data.jsonl "$TARGET/"
fi

if [ -f data/grpo_prompts.jsonl ]; then
    echo "    Copying GRPO prompts..."
    cp data/grpo_prompts.jsonl "$TARGET/"
fi

# NNDSS generated pairs
if [ -d data/nndss_pairs ] && [ "$(ls -A data/nndss_pairs)" ]; then
    echo "    Copying NNDSS pairs..."
    cp -r data/nndss_pairs "$TARGET/"
fi

# BIRD SQLite databases
if [ -d data/bird_databases ] && [ "$(ls -A data/bird_databases)" ]; then
    echo "    Copying BIRD databases..."
    cp -r data/bird_databases/* "$TARGET/bird_databases/"
fi

echo "==> Upload complete. Contents:"
find "$TARGET" -maxdepth 2 -type f | head -20
echo "..."
du -sh "$TARGET"
